/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app_kasir;

/**
 *
 * @author ariya
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextTitle = new javax.swing.JLabel();
        BGTitle = new javax.swing.JLabel();
        BGGreen = new javax.swing.JLabel();
        Btn = new javax.swing.JLabel();
        BGWhite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 80));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        TextTitle.setText("KASIR RUMAH KUCING");
        jPanel1.add(TextTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        BGTitle.setIcon(new javax.swing.ImageIcon("D:\\Koding-Tugas-Kampus\\App_Kasir\\src\\img\\dashboard 3.png")); // NOI18N
        jPanel1.add(BGTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BGGreen.setIcon(new javax.swing.ImageIcon("D:\\Koding-Tugas-Kampus\\App_Kasir\\src\\img\\dashboard.png")); // NOI18N
        jPanel1.add(BGGreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Btn.setIcon(new javax.swing.ImageIcon("D:\\Koding-Tugas-Kampus\\App_Kasir\\src\\img\\buton 1.png")); // NOI18N
        jPanel1.add(Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        BGWhite.setIcon(new javax.swing.ImageIcon("D:\\Koding-Tugas-Kampus\\App_Kasir\\src\\img\\dashboard 2.png")); // NOI18N
        jPanel1.add(BGWhite, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BGGreen;
    private javax.swing.JLabel BGTitle;
    private javax.swing.JLabel BGWhite;
    private javax.swing.JLabel Btn;
    private javax.swing.JLabel TextTitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
